global:
  scrape_interval:     10s
  evaluation_interval: 10s
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          host_name: "plotter"
