{
 "title": "SMART",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall disk health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartmon_device_smart_healthy" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=\"temperature_celsius\"}"
    }
   ]
  },
  {
   "title": "TBW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=\"total_lbas_written\"}*4096"
    }
   ]
  },
  {
   "title": "Wear level %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_attr_value{name=\"wear_leveling_count\"}"
    }
   ]
  }
 ]
}